/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EmployeeProfile;
import model.EmployeeProfileRecordHistory;

/**
 *
 * @author Harshada
 */
public class DeleteJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeleteJPanel
     */
    EmployeeProfileRecordHistory empProfileHistory;
    
    //Constructor
    public DeleteJPanel(EmployeeProfileRecordHistory empProfileHistory) {
        initComponents();
        this.empProfileHistory = empProfileHistory;
        populateEmployeeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateTitle = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmpTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreateTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCreateTitle.setForeground(new java.awt.Color(255, 51, 51));
        lblCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateTitle.setText("Delete Employee");
        add(lblCreateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 197, 32));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 120, 40));

        EmpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee ID", "Age", "Gender", "Start Date", "Team Info", "Position Title", "Phone No", "Email Address", "Level"
            }
        ));
        jScrollPane1.setViewportView(EmpTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 720, 110));
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = EmpTable.getSelectedRow();
        //Check if row selected
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) EmpTable.getModel();
        EmployeeProfile selectedEmployee = (EmployeeProfile) model.getValueAt(selectedRowIndex, 0);
        empProfileHistory.deleteEmployee(selectedEmployee);
        JOptionPane.showMessageDialog(this, "Employee record has been deleted");
        populateEmployeeTable();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmpTable;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateTitle;
    // End of variables declaration//GEN-END:variables

    private void populateEmployeeTable() {
        DefaultTableModel model = (DefaultTableModel) EmpTable.getModel();
        model.setRowCount(0);
        for (EmployeeProfile profile : empProfileHistory.getEmpProfileHistory()) {
          Object[] row = new Object[10];
          row[0] = profile;
          row[1] = profile.getEmpId();
          row[2] = profile.getAge();
          row[3] = profile.getGender();
          row[4] = profile.getEmp_startDate();
          row[5] = profile.getEmp_teamInfo();
          row[6] = profile.getEmp_positionTitle(); 
          row[7] = profile.getEmp_cellPhoneNo();
          row[8] = profile.getEmailAddress();
          row[9] = profile.getEmp_level(); 
          model.addRow(row);
        }
    }
}
