/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.EmployeeProfile;
import model.EmployeeProfileRecordHistory;

/**
 *
 * @author Harshada
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    DefaultTableModel model;
    EmployeeProfileRecordHistory empProfileHistory;

    public SearchJPanel(EmployeeProfileRecordHistory empProfileHistory) {
        initComponents();
        this.empProfileHistory = empProfileHistory;
        populateEmployeeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearchTitle = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmpTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSearchTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSearchTitle.setForeground(new java.awt.Color(204, 0, 204));
        lblSearchTitle.setText("Search Employee");
        add(lblSearchTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 150, 40));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 51, 255));
        lblSearch.setText("Enter Search String:");
        add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 67, 130, 40));

        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255), 2));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 74, 240, 30));

        EmpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Phone No", "Email Address"
            }
        ));
        jScrollPane1.setViewportView(EmpTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 670, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String searchString = txtSearch.getText();
        Search(searchString);
    }//GEN-LAST:event_txtSearchKeyReleased

    public void Search(String str) {
        model = (DefaultTableModel) EmpTable.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        EmpTable.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmpTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearchTitle;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void populateEmployeeTable() {
        DefaultTableModel model = (DefaultTableModel) EmpTable.getModel();
        model.setRowCount(0);
        for (EmployeeProfile profile : empProfileHistory.getEmpProfileHistory()) {
          Object[] row = new Object[10];
          row[0] = profile;
          row[1] = profile.getEmpId();
          row[2] = profile.getAge();
          row[3] = profile.getGender();
          row[4] = profile.getEmp_startDate();
          row[5] = profile.getEmp_teamInfo();
          row[6] = profile.getEmp_positionTitle(); 
          row[7] = profile.getEmp_cellPhoneNo();
          row[8] = profile.getEmailAddress();
          row[9] = profile.getEmp_level(); 
          model.addRow(row);
        }
         model.fireTableDataChanged();

    }
}
