/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.EmployeeProfile;
import model.EmployeeProfileRecordHistory;

/**
 *
 * @author Harshada
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    //Creating objects
    EmployeeProfileRecordHistory empProfileHistory;
    EmployeeProfile empProfile;

    //Constructor
    public UpdateJPanel(EmployeeProfileRecordHistory empProfileHistory, EmployeeProfile empProfile) {
        initComponents();
        this.empProfileHistory = empProfileHistory;
        this.empProfile = empProfile;
        populateEmployeeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateTitle = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        lblEmpID = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblTeamInfo = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JTextField();
        txtEmpID = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmpTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnUpdatePhoto = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreateTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCreateTitle.setForeground(new java.awt.Color(51, 204, 0));
        lblCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateTitle.setText("Update Employee");
        add(lblCreateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 2, 197, 30));

        lblEmpName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpName.setText("Employee Name:");
        add(lblEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 30));

        lblEmpID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpID.setText("Employee ID:");
        add(lblEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 30));

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 80, 30));

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setText("Gender:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 40));

        lblTeamInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTeamInfo.setText("Team Info:");
        add(lblTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 90, 30));

        lblPositionTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPositionTitle.setText("Position Title: ");
        add(lblPositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 90, 30));

        lblPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhoneNo.setText("Phone Number:");
        add(lblPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 100, 20));

        lblEmailAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmailAddress.setText("Email Address:");
        add(lblEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 90, 30));

        txtEmpName.setBackground(new java.awt.Color(255, 255, 234));
        add(txtEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 150, 30));

        txtEmpID.setEditable(false);
        txtEmpID.setBackground(new java.awt.Color(255, 255, 234));
        add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 150, 30));

        txtAge.setBackground(new java.awt.Color(255, 255, 234));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 150, 30));

        txtGender.setBackground(new java.awt.Color(255, 255, 234));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 150, 30));

        txtTeamInfo.setBackground(new java.awt.Color(255, 255, 234));
        add(txtTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 143, 30));

        txtPositionTitle.setBackground(new java.awt.Color(255, 255, 234));
        add(txtPositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 143, 30));

        txtPhoneNo.setBackground(new java.awt.Color(255, 255, 234));
        add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 143, 30));

        txtEmailAddress.setBackground(new java.awt.Color(255, 255, 234));
        add(txtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 143, 30));

        btnView.setBackground(new java.awt.Color(255, 255, 234));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnView.setText("View Record");
        btnView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0), 2));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Start Date:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 100, 30));

        txtStartDate.setBackground(new java.awt.Color(255, 255, 234));
        add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Level:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 70, 30));

        txtLevel.setBackground(new java.awt.Color(255, 255, 234));
        add(txtLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 140, 30));

        btnUpdate.setBackground(new java.awt.Color(204, 255, 153));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updated.png"))); // NOI18N
        btnUpdate.setText("Update Record");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0), 2));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 120, 30));

        EmpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee ID", "Age", "Gender", "Start Date", "Team Info", "Position Title", "Phone No", "Email Address", "Level"
            }
        ));
        jScrollPane1.setViewportView(EmpTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 780, 110));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Photo:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        btnUpdatePhoto.setBackground(new java.awt.Color(255, 255, 234));
        btnUpdatePhoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdatePhoto.setText("Update Photo");
        btnUpdatePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePhotoActionPerformed(evt);
            }
        });
        add(btnUpdatePhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 272, -1, 30));

        lblPhoto.setEnabled(false);
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 50, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = EmpTable.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) EmpTable.getModel();

        //Setting text
        EmployeeProfile selectedEmployee = (EmployeeProfile) model.getValueAt(selectedRowIndex, 0);
        txtEmpName.setText(selectedEmployee.getEmpName());
        txtEmpID.setText(String.valueOf(selectedEmployee.getEmpId()));
        txtAge.setText(String.valueOf(selectedEmployee.getAge()));
        txtGender.setText(selectedEmployee.getGender());
        txtStartDate.setText(selectedEmployee.getEmp_startDate());
        txtTeamInfo.setText(selectedEmployee.getEmp_teamInfo());
        txtLevel.setText(selectedEmployee.getEmp_level());
        txtEmailAddress.setText(selectedEmployee.getEmailAddress());
        txtPositionTitle.setText(selectedEmployee.getEmp_positionTitle());
        txtPhoneNo.setText(selectedEmployee.getEmp_cellPhoneNo());
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) EmpTable.getModel();
        //Get selected row values
        if (EmpTable.getSelectedRowCount() == 1) {
            EmpTable.setValueAt(txtEmpName.getText(), EmpTable.getSelectedRow(), 0);
            EmpTable.setValueAt(txtEmpID.getText(), EmpTable.getSelectedRow(), 1);
            EmpTable.setValueAt(txtAge.getText(), EmpTable.getSelectedRow(), 2);
            EmpTable.setValueAt(txtGender.getText(), EmpTable.getSelectedRow(), 3);
            EmpTable.setValueAt(txtStartDate.getText(), EmpTable.getSelectedRow(), 4);
            EmpTable.setValueAt(txtTeamInfo.getText(), EmpTable.getSelectedRow(), 5);
            EmpTable.setValueAt(txtPositionTitle.getText(), EmpTable.getSelectedRow(), 6);
            EmpTable.setValueAt(txtPhoneNo.getText(), EmpTable.getSelectedRow(), 7);
            EmpTable.setValueAt(txtEmailAddress.getText(), EmpTable.getSelectedRow(), 8);
            EmpTable.setValueAt(txtLevel.getText(), EmpTable.getSelectedRow(), 9);

            JOptionPane.showMessageDialog(this, "Record Updated Successfully");
            
            //Setting text to blank once record has been inserted
            txtEmailAddress.setText("");
            txtPhoneNo.setText("");
            txtPositionTitle.setText("");
            txtTeamInfo.setText("");
            txtStartDate.setText("");
            txtGender.setText("");
            txtEmpID.setText("");
            txtEmpName.setText("");
            txtAge.setText("");
            txtLevel.setText("");
            lblPhoto.setText("");
            
        } else {
            if (EmpTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is empty");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a single record to update");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdatePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePhotoActionPerformed
        // TODO add your handling code here:
        //Update Photo
        JFileChooser uploadPhoto = new JFileChooser();
        FileNameExtensionFilter fileExtension = new FileNameExtensionFilter("*.images", "jpg", "jpeg", "png");
        uploadPhoto.addChoosableFileFilter(fileExtension);
        int selectPhoto = uploadPhoto.showOpenDialog(null);
        if (selectPhoto == JFileChooser.APPROVE_OPTION) {
            File imageUploaded = uploadPhoto.getSelectedFile();
            String imagePath = imageUploaded.getAbsolutePath();
            JOptionPane.showMessageDialog(null, "Photo uploaded Successfully.");
            ImageIcon imageIcon = new ImageIcon(imagePath);
            Image imageDetails = imageIcon.getImage().getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH);
            empProfile.setPhoto(imagePath);
            lblPhoto.setIcon(new ImageIcon(empProfile.getPhoto()));
        }
    }//GEN-LAST:event_btnUpdatePhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmpTable;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdatePhoto;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCreateTitle;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblEmpName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables

    private void populateEmployeeTable() {
        DefaultTableModel model = (DefaultTableModel) EmpTable.getModel();
        model.setRowCount(0);
        for (EmployeeProfile profile : empProfileHistory.getEmpProfileHistory()) {
            Object[] row = new Object[10];
            row[0] = profile;
            row[1] = profile.getEmpId();
            row[2] = profile.getAge();
            row[3] = profile.getGender();
            row[4] = profile.getEmp_startDate();
            row[5] = profile.getEmp_teamInfo();
            row[6] = profile.getEmp_positionTitle();
            row[7] = profile.getEmp_cellPhoneNo();
            row[8] = profile.getEmailAddress();
            row[9] = profile.getEmp_level();
            model.addRow(row);
        }
    }
}
