/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EmployeeProfile;
import model.EmployeeProfileRecordHistory;

/**
 *
 * @author Harshada
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    EmployeeProfileRecordHistory empProfileHistory;
    EmployeeProfile empProfile;

    public ViewJPanel(EmployeeProfileRecordHistory empProfileHistory, EmployeeProfile empProfile) {
        initComponents();
        this.empProfileHistory = empProfileHistory;
        this.empProfile = empProfile;
        //displayEmployeeInfo();
        populateEmployeeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCreateTitle = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        lblEmpID = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblTeamInfo = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JTextField();
        txtEmpID = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmpTable = new javax.swing.JTable();
        lblPhoto = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreateTitle.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblCreateTitle.setForeground(new java.awt.Color(255, 153, 0));
        lblCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateTitle.setText("View Employee");
        add(lblCreateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 197, 32));

        lblEmpName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpName.setText("Employee Name:");
        add(lblEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        lblEmpID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpID.setText("Employee ID:");
        add(lblEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 30));

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 80, 30));

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setText("Gender:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 70, 30));

        lblStartDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStartDate.setText("Start Date:");
        add(lblStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 70, 40));

        lblLevel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLevel.setText("Level:");
        add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 100, 30));

        lblTeamInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTeamInfo.setText("Team Info:");
        add(lblTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 100, 30));

        lblPositionTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPositionTitle.setText("Position Title: ");
        add(lblPositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 110, 30));

        lblPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhoneNo.setText("Phone Number:");
        add(lblPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 110, 30));

        lblEmailAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmailAddress.setText("Email Address:");
        add(lblEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 110, 30));

        txtEmpName.setBackground(new java.awt.Color(255, 255, 234));
        add(txtEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 150, 30));

        txtEmpID.setBackground(new java.awt.Color(255, 255, 234));
        add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 150, 30));

        txtAge.setBackground(new java.awt.Color(255, 255, 234));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 150, 30));

        txtGender.setBackground(new java.awt.Color(255, 255, 234));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 150, 30));

        txtStartDate.setBackground(new java.awt.Color(255, 255, 234));
        add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 150, 30));

        txtLevel.setBackground(new java.awt.Color(255, 255, 234));
        add(txtLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 160, 30));

        txtTeamInfo.setBackground(new java.awt.Color(255, 255, 234));
        add(txtTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 160, 30));

        txtPositionTitle.setBackground(new java.awt.Color(255, 255, 234));
        add(txtPositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 160, 30));

        txtPhoneNo.setBackground(new java.awt.Color(255, 255, 234));
        add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 160, 30));

        txtEmailAddress.setBackground(new java.awt.Color(255, 255, 234));
        add(txtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 160, 30));

        btnView.setBackground(new java.awt.Color(255, 255, 204));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 153, 51));
        btnView.setText("View");
        btnView.setBorder(null);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 100, 30));

        EmpTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee ID", "Age", "Gender", "Start Date", "Team Info", "Position Title", "Phone No", "Email Address", "Level"
            }
        ));
        jScrollPane1.setViewportView(EmpTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 780, 120));
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 150, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
           if (EmpTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is empty");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a single record to update");
            }
        int selectedRowIndex = EmpTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) EmpTable.getModel();
        EmployeeProfile selectedEmployee = (EmployeeProfile) model.getValueAt(selectedRowIndex, 0);
        txtEmpName.setText(selectedEmployee.getEmpName());
        txtEmpID.setText(String.valueOf(selectedEmployee.getEmpId()));
        txtAge.setText(String.valueOf(selectedEmployee.getAge()));
        txtGender.setText(selectedEmployee.getGender());
        txtStartDate.setText(selectedEmployee.getEmp_startDate());
        txtTeamInfo.setText(selectedEmployee.getEmp_teamInfo());
        txtLevel.setText(selectedEmployee.getEmp_level());
        txtEmailAddress.setText(selectedEmployee.getEmailAddress());
        txtPositionTitle.setText(selectedEmployee.getEmp_positionTitle());
        txtPhoneNo.setText(selectedEmployee.getEmp_cellPhoneNo());
        lblPhoto.setIcon(new ImageIcon(empProfile.getPhoto()));
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmpTable;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCreateTitle;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblEmpName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables

    private void populateEmployeeTable() {
        DefaultTableModel model = (DefaultTableModel) EmpTable.getModel();
        model.setRowCount(0);

        for (EmployeeProfile profile : empProfileHistory.getEmpProfileHistory()) {

            Object[] row = new Object[10];
            row[0] = profile;
            row[1] = profile.getEmpId();
            row[2] = profile.getAge();
            row[3] = profile.getGender();
            row[4] = profile.getEmp_startDate();
            row[5] = profile.getEmp_teamInfo();
            row[6] = profile.getEmp_positionTitle();
            row[7] = profile.getEmp_cellPhoneNo();
            row[8] = profile.getEmailAddress();
            row[9] = profile.getEmp_level();
            model.addRow(row);
        }
    }
}
